import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

test("home exposes daily check-in and the directly imported official site", () => {
  const app = readFileSync(new URL("../public/app.js", import.meta.url), "utf8");
  const start = app.indexOf("async function home()");
  const end = app.indexOf("async function legacyHome()", start);
  const home = app.slice(start, end);
  assert.match(home, /data-home-inline="daily" aria-pressed="true"/);
  assert.match(home, /id="homeDailyPanel" class="ak-daily-panel ak-content-panel" data-content-panel="daily"/);
  assert.match(home, /await daily\("#homeDailyPanel"\)/);
  assert.match(home, /class="ak-official-import ak-content-panel hidden"/);
  assert.match(home, /class="ak-official-import-frame"/);
  assert.match(home, /src="\/akaffit-official"/);
  assert.match(home, /data-content-view="youtube"><svg[\s\S]*?<span>YouTube<\/span>/);
  assert.match(home, /data-content-view="facebook"><svg[\s\S]*?<span>Facebook<\/span>/);
  assert.match(home, /data-content-view="instagram"><svg[\s\S]*?<span>Instagram<\/span>/);
  assert.match(home, /data-content-view="official"><svg[\s\S]*?<span>官方網站<\/span>/);
  assert.match(home, /data-content-view="academy"><svg[\s\S]*?<span>咖啡學院<\/span>/);
  assert.match(home, /data-content-panel="academy"[\s\S]*goldenJourneyMarkup\(\)/);
  assert.match(app, /data-academy-course="golden-journey">醇金之旅/);
  assert.match(home, /data-content-panel="facebook"/);
  assert.match(home, /data-content-panel="instagram"/);
  assert.match(home, /data-content-panel="youtube"/);
  assert.match(home, /loadAkaffitYoutube\(\)/);
  assert.doesNotMatch(home, /\/v1\/blog\/posts\?limit=6|A-KAFFIT JOURNAL|ak-brand-story|ak-craft-section/);
  assert.doesNotMatch(home, /聯絡我們|電話|信箱|地址|service@|mailto:|tel:/);
  assert.doesNotMatch(home, />更多功能</);
  assert.doesNotMatch(home, /class="ak-stats"/);
  const features = home.slice(home.indexOf('<div class="ak-feature-grid">'), home.indexOf('</div>', home.indexOf('<div class="ak-feature-grid">')));
  assert.equal((features.match(/<button(?: type="button")? data-home-(?:action|inline)=/g) || []).length, 6);
  assert.match(features, /cardCollection[\s\S]*data-home-action="card"[\s\S]*data-home-inline="daily"[\s\S]*smartMatch[\s\S]*calendar[\s\S]*tasks/);
  assert.doesNotMatch(features, /data-home-action="zodiac"/);
  assert.match(features, /data-home-action="card"[\s\S]*電子名片/);
  assert.doesNotMatch(features, /data-home-action="courses"|data-home-action="wallet"/);
  assert.match(features, /個人行程/);
  assert.doesNotMatch(features, /<i>/);
  assert.doesNotMatch(home, /ak-moment-banner/);
});

test("admin is A-kaffit-owned and exposes the Mira-style check-in module", () => {
  const html = readFileSync(new URL("../public/admin.html", import.meta.url), "utf8");
  const routeHtml = readFileSync(new URL("../public/admin/index.html", import.meta.url), "utf8");
  const adminJs = readFileSync(new URL("../public/admin.js", import.meta.url), "utf8");
  const adminCss = readFileSync(new URL("../public/admin.css", import.meta.url), "utf8");
  const worker = readFileSync(new URL("../src/index.js", import.meta.url), "utf8");
  const wrangler = readFileSync(new URL("../wrangler.jsonc", import.meta.url), "utf8");
  for (const page of [html, routeHtml]) {
    assert.match(page, /data-page="carousel"(?! hidden)/);
    assert.match(page, /簽到贈點活動目錄/);
    assert.match(page, /簽到內容管理/);
    assert.match(page, /新增簽到內容/);
    assert.match(page, /活動狀態（可切換）/);
    assert.doesNotMatch(page, /data-page="blog"|data-content="blog"|網誌管理/);
    assert.doesNotMatch(page, /mlm\.fangwl591021\.workers\.dev|MLM 主控台|返回 MLM/);
    assert.match(page, /\/admin\.css\?v=20260813-1/);
    assert.match(page, /\/admin\.js\?v=20260825-2/);
  }
  assert.match(adminJs, /data-template-directory-action="toggle"/);
  assert.match(adminJs, /role="switch"/);
  assert.match(adminJs, /toggleCheckinGroupStatus/);
  assert.match(adminCss, /\.templateDirStatusToggle\.is-active/);
  assert.doesNotMatch(adminJs, /loadBlogPosts|網誌管理/);
  assert.doesNotMatch(adminCss, /\.nav-item\[data-page="carousel"\]|\[data-go="carousel"\]/);
  assert.doesNotMatch(worker, /super-admin-status|mlm_super_admin|url\.pathname==="\/admin\/sso"/);
  assert.doesNotMatch(wrangler, /"\/admin\/sso"/);
  assert.match(wrangler, /"\/admin\/\*"/);
  assert.match(worker, /cache-control", "no-store, no-cache, must-revalidate/);
});
